# Use Maven base image with Java 17
FROM maven:3.9.6-eclipse-temurin-17

# Create working directory
WORKDIR /app

# Copy the application source code into the container
COPY . .

# Build the app using mvn package
RUN mvn package -DskipTests

# Expose port 8080
EXPOSE 8080

# Run the app on jar file
CMD ["java", "-jar", "target/demo-0.0.1-SNAPSHOT.jar"]