# Use Java 17 base image
FROM eclipse-temurin:17-jre-jammy

# Create working directory
WORKDIR /app

# Copy the JAR file into the container
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the app on jar file
CMD ["java", "-jar", "app.jar"]
